name: CI

on:
  push:
    branches:
      - main
      - trunk-merge/**
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: [3.7, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependecies
        run: |
          python -m pip install --upgrade pip
          pip install jaxlib jax-md jaxopt pytest matplotlib

      - name: Install pysages
        run: pip install .

      - name: Run tests
        run: |
          pytest
          mkdir /tmp/test_plots
          mv *.pdf /tmp/test_plots

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test_plots
          path: /tmp/test_plots

  doc-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install python dependecies
        run: |
          python -m pip install --upgrade pip
          pip install jaxlib jax-md jaxopt pytest pylint flake8
          pip install -r docs/requirements.txt
      - name: Install pysages
        run: pip install .
      - name: Build documentation
        run: cd docs && sphinx-build -b spelling -W --keep-going source build
